version: "3"

services:
  mysql:
    build:
      context: mysql/.
      args:
        - MYSQL_IMAGE_TAG=${MYSQL_IMAGE_TAG}
    image: ${MYSQL_IMAGE_TAG}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:${MYSQL_PORT}
    volumes:
      - ${MYSQL_VOL_DATA}:/var/lib/mysql
      - ${MYSQL_VOL_CONF}:/etc/mysql/conf.d
    networks:
      default:
        ipv4_address: ${MYSQL_IP}
  nginx:
    build:
      context: nginx/.
      args:
        - NGINX_IMAGE_TAG=${NGINX_IMAGE_TAG}
    image: ${NGINX_IMAGE_TAG}
    container_name: nginx
    ports:
      - 80:${NGINX_PORT}
    environment:
      NGINX_HOSTS: ${NGINX_HOSTS}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_WWW_PATH: ${NGINX_WWW_PATH}
      DEALPACK_IP: ${DEALPACK_IP}
    volumes:
      - ${NGINX_SRC_PATH}:${NGINX_WWW_PATH}
      - ${NGINX_CONF}:/etc/nginx/nginx.conf
      - ${NGINX_TEMPLATE}:/tmp/dealpack.conf.template
    command: >-
      /bin/sh -c "envsubst '$$NGINX_PORT $$NGINX_HOSTS $$DEALPACK_IP' < /tmp/dealpack.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      default:
        ipv4_address: ${NGINX_IP}
  dealpack:
    build:
      context: .
      args:
        - DEALPACK_IMAGE_TAG=${DEALPACK_IMAGE_TAG}
        - WEB_USER=${WEB_USER}
        - WEB_USER_ID=${WEB_USER_ID}
        - WEB_GROUP=${WEB_GROUP}
        - WEB_GROUP_ID=${WEB_GROUP_ID}
        - WEB_USER_PASSWORD=${WEB_USER_PASSWORD}
        - NVM_VERSION=${NVM_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - NPM_REGISTRY=${NPM_REGISTRY}
        - YARN_VERSION=${YARN_VERSION}
        - WORK_PATH=${WORK_PATH}/${DEALPACK_DIR}
        - DEALPACK_DIR=${DEALPACK_DIR}
    image: ${DEALPACK_IMAGE_TAG}
    container_name: ${DEALPACK_CONTAINER_NAME}
    environment:
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      DEALPACK_WORK_PATH: ${WORK_PATH}
      DEALPACK_DIR: ${DEALPACK_DIR}
    ports:
      - ${DEALPACK_HOST_PORT}:80
    volumes:
      - ${DEALPACK_HOST_PATH}:${WORK_PATH}/${DEALPACK_DIR}
    #command: /bin/sh -c "while :; do sleep 10; done"
    entrypoint:
      - /home/${WEB_USER}/entrypoint.sh
    networks:
      default:
        ipv4_address: ${DEALPACK_IP}

networks:
  default:
    external:
      name: ${NETWORK_NAME}
